name: Build
on: [ push, pull_request ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.14, 1.15]
        ursa-version: ['0.3.2', '0.3.4']
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test using Ursa ${{ matrix.ursa-version }}
      uses: docker://m00sey/ursa_${{ matrix.ursa-version }}:latest
      run: |
        make test
