name: Build
on: [ push, pull_request ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-20.04
    container: m00sey/ursa_0.3.2:latest
    strategy:
      matrix:
        go-version: [1.14, 1.15]
        # ursa-version: ['0.3.2', '0.3.4']
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test using Ursa ${{ matrix.ursa-version }}
      run: |
        make test
